### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheAstral182** [gamendegamer321/RgbNuke#2]
When there's one player at server stars an rgb nuke - round ends. Also, please, can you make a config where i can changed the name of an Audio Player bot, please?

**Comment by gamendegamer321** [comment]
I've added the option to change the name of the bot.
As for the round ending, there is not much I can do about that as far as I know. For the audio bot to work it needs to create a new connection to the server and, even though it doesn't count as a player, it's still a second connection allowing the round to end.
You can prevent it by enabling round lock (if you have the permissions).
