### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMNM** [gamendegamer321/RgbNuke#3]
Whenever I start the rgbnuke there is no audio and when I check the files there is no audio file or audio

**Comment by gamendegamer321** [comment]
That is correct, you need to add your own audio file.
If I'm not mistaken for the [SCPSL Audio Api](https://github.com/CedModV2/SCPSLAudioApi/tree/master) it should be a .ogg file with mono audio and a sample rate of 48000.
